# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

baselineArray <- function(x, bl, dims, bldims, tidx, per, rest, method) {
    .Call(`_ravetools_baselineArray`, x, bl, dims, bldims, tidx, per, rest, method)
}

collapser_cplx <- function(x, keep, method = 1L, average = 0L) {
    .Call(`_ravetools_collapser_cplx`, x, keep, method, average)
}

collapser_real <- function(x, keep, method = 1L, average = 0L) {
    .Call(`_ravetools_collapser_real`, x, keep, method, average)
}

fftw_r2c <- function(data, HermConj = 1L, fftwplanopt = 0L, ret = NULL, inplace = FALSE) {
    .Call(`_ravetools_fftw_r2c`, data, HermConj, fftwplanopt, ret, inplace)
}

mvfftw_r2c <- function(data, fftwplanopt = 0L, ret = NULL, inplace = FALSE) {
    .Call(`_ravetools_mvfftw_r2c`, data, fftwplanopt, ret, inplace)
}

fftw_c2c <- function(data, inverse = 0L, ret = NULL, inplace = FALSE) {
    .Call(`_ravetools_fftw_c2c`, data, inverse, ret, inplace)
}

fftw_c2r <- function(data, HermConj = 1L, ret = NULL, inplace = FALSE) {
    .Call(`_ravetools_fftw_c2r`, data, HermConj, ret, inplace)
}

conjugate <- function(data) {
    .Call(`_ravetools_conjugate`, data)
}

shiftArray <- function(x, alongIdx, unitIdx, shiftAmount) {
    .Call(`_ravetools_shiftArray`, x, alongIdx, unitIdx, shiftAmount)
}

